server.port=8087

#data source
spring.jpa.database-platform=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/sbamicro_organizationdb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

#JPA vendor Hibernate config
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true

#Eureka Server Url
eureka.instance.client.serve
